### ISSUE TITLE
Maschine Studio?

### ISSUE THREAD

**Issue by daslicht** [jhorology/nks-presets-collection#4]
Hi,
Does that also work with Maschine Studio , please ?

**Comment by jhorology** [comment]
Yes, I don't have a maschine, but I heard some maschine users using this presets.

**Comment by daslicht** [comment]
Is there a also a way to add custom images ?

[see here](https://www.gearslutz.com/board/9584884-post1.html)

**Comment by daslicht** [comment]
Tomorrow I get a Maschine Studio and will be able to report if it works :)

**Comment by jhorology** [comment]
How was a Maschine?
hehe, I probably buy a Maschine Jam.

**Comment by daslicht** [comment]
I love the studio
