### ISSUE TITLE
gulp-gunzip seems to be missing in package.json

### ISSUE THREAD

**Issue by fyyyyy** [jhorology/nks-presets-collection#8]
https://github.com/jhorology/nks-presets-collection/blob/3479945f5b6fe0276482ef8dff8d68e852f6c4e0/lib/common-tasks.coffee#L25

**Comment by daslicht** [comment]
?

**Comment by daslicht** [comment]
?
https://github.com/jhorology/nks-presets-collection/blob/master/package.json#L27

**Comment by fyyyyy** [comment]
this is gzip

this works:
```
    "gulp-gunzip": "0.0.3",
    "gulp-gzip": "^1.4.0",
```

**Comment by daslicht** [comment]
yeah saw it that why i remove my comment, just male a pull request and add it to the package json :)

**Comment by jhorology** [comment]
Thank you, I just merged pull request.
